default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  port: 5432

development:
  <<: *default
  database: hackaton_api_development

test:
  <<: *default
  database: hackaton_api_test

production:
  <<: *default
  database: hackaton_api_production
  username: myapp_user
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
