# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: hackaton
  password: password1
  host: localhost

development:
  <<: *default
  database: your_project_development

test:
  <<: *default
  database: your_project_test

production:
  <<: *default
  database: your_project_production
  username: hackaton
  password: password1
